CREATE TABLE TBCIS.DAILY_CHARGES_INEN_S_TEMP
(
  REF_NUM                 NUMBER(10),
  INVO_REF_NUM            NUMBER(10),
  SEC_AMT                 NUMBER(16,4),
  ROUNDING_INDICATOR      VARCHAR2(1 BYTE),
  UNDER_DISPUTE           VARCHAR2(1 BYTE),
  CREATED_BY              VARCHAR2(15 BYTE),
  DATE_CREATED            DATE,
  AMT_IN_CURR             NUMBER(16,4),
  BILLING_SELECTOR        VARCHAR2(3 BYTE),
  FCIT_TYPE_CODE          VARCHAR2(3 BYTE),
  TATY_TYPE_CODE          VARCHAR2(3 BYTE),
  SUSG_REF_NUM            NUMBER(10),
  IADN_REF_NUM            NUMBER(10),
  CURR_CODE               VARCHAR2(3 BYTE),
  VMCT_TYPE_CODE          VARCHAR2(3 BYTE),
  LAST_UPDATED_BY         VARCHAR2(15 BYTE),
  DATE_UPDATED            DATE,
  DESCRIPTION             VARCHAR2(60 BYTE),
  SEC_AMT_TAX             NUMBER(16,4),
  AMT_TAX_CURR            NUMBER(16,4),
  MANUAL_ENTRY            VARCHAR2(1 BYTE),
  EVRE_COUNT              NUMBER,
  EVRE_DURATION           NUMBER,
  MODULE_REF              VARCHAR2(4 BYTE),
  SEC_FIXED_CHARGE_VALUE  NUMBER(16,4),
  EVRE_CHAR_USAGE         NUMBER,
  PRINT_REQUIRED          VARCHAR2(1 BYTE),
  VMCT_RATE_VALUE         NUMBER(5,2),
  NUM_OF_DAYS             NUMBER(2),
  EVRE_DATA_VOLUME        NUMBER,
  MAAS_REF_NUM            NUMBER(10),
  CADC_REF_NUM            NUMBER(10),
  FCDT_TYPE_CODE          VARCHAR2(4 BYTE),
  SEC_FF_DISC_AMT         NUMBER(16,4),
  SEC_CURR_CODE           VARCHAR2(3 BYTE),
  EEK_AMT                 NUMBER(16,4),
  AMT_TAX                 NUMBER(16,4),
  PRI_CURR_CODE           VARCHAR2(3 BYTE),
  FF_DISC_AMT             NUMBER(16,4),
  FIXED_CHARGE_VALUE      NUMBER(16,4),
  SEC_ACC_AMOUNT          NUMBER(16,4),
  ACC_AMOUNT              NUMBER(16,4),
  BILLING_SELECTOR_TEXT   VARCHAR2(40 BYTE),
  ENTRY_TEXT              VARCHAR2(40 BYTE),
  ADDITIONAL_ENTRY_TEXT   VARCHAR2(40 BYTE),
  MAAC                    NUMBER,
  INVO_AMOUNT             NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
