CREATE TABLE TBCIS.DAILY_CHARGES_DESCR_S_TEMP
(
  BICY_CYCLE_CODE        VARCHAR2(10 BYTE),
  MAAC                   NUMBER,
  SUSG                   NUMBER,
  SERV_NUM               NUMBER,
  SETY_REF_NUM           NUMBER,
  SERVICE_NAME           VARCHAR2(40 BYTE),
  SEPT_TYPE_CODE         VARCHAR2(10 BYTE),
  SEPT_DESCRIPTION       VARCHAR2(40 BYTE),
  SEPV_REF_NUM           NUMBER,
  SEPV_DESCRIPTION       VARCHAR2(40 BYTE),
  PACKET_DISCOUNT        VARCHAR2(10 BYTE),
  STARTS                 DATE,
  ENDS                   DATE,
  MAIN_DAYS              NUMBER,
  CHARGE_VALUE           NUMBER,
  PRICE_TYPE             VARCHAR2(10 BYTE),
  CURR_CODE              VARCHAR2(3 BYTE),
  PERIOD_CHARGE          NUMBER,
  INCL_DISC              NUMBER,
  FCIT_BILLING_SELECTOR  VARCHAR2(10 BYTE),
  FCIT_TYPE_CODE         VARCHAR2(10 BYTE),
  FCIT_TATY_TYPE_CODE    VARCHAR2(10 BYTE),
  FCIT_BISE              VARCHAR2(40 BYTE),
  FCIT_DESC              VARCHAR2(40 BYTE),
  DISC_START             DATE,
  DISC_END               DATE,
  DISC_DAYS              NUMBER,
  DISCOUNT               NUMBER,
  DISCOUNT_CODE          VARCHAR2(40 BYTE),
  DISCOUNT_DESCRIPTION   VARCHAR2(40 BYTE),
  DISC_BILLING_SELECTOR  VARCHAR2(10 BYTE),
  FCIT_FCDT_TYPE_CODE    VARCHAR2(10 BYTE),
  DISC_BISE              VARCHAR2(40 BYTE),
  DISC_DESCRIPTION       VARCHAR2(40 BYTE),
  CADC_REF_NUM           NUMBER,
  SUDI_REF_NUM           NUMBER,
  CRM                    VARCHAR2(1 BYTE),
  BILLED_INVO_END        DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
